### ISSUE TITLE
Retain flag on published topics

### ISSUE THREAD

**Issue by robynjayqueerie** [bersim/OpenKPs#3]
I was looking to see if your code has the option to set the retain flag on published topics. I don't see any mention of it. We need that feature for our projects.
http://www.hivemq.com/blog/mqtt-essentials-part-8-retained-messages 
Thanks

**Comment by bersim** [comment]
Add option Retain. Example [config](https://github.com/bersim/OpenKPs/releases/download/5.0.7/KpMQTT.7z)
