### ISSUE TITLE
Sending commands

### ISSUE THREAD

**Issue by 2mik** [bersim/OpenKPs#6]
Добрый день!
Возможно ли реализовать отправку команд по MQTT?
Обсуждение с пользователем на эту тему http://forum.rapidscada.org/?topic=send-a-command-through-mqtt/

**Comment by bersim** [comment]
Добрый день!
Эта функциональность запланирована в будущих версиях. На текущий момент
нужно будет еще понять нужно ли трансформировать команды в текстовый
формат. Или просто выполнять роль шлюза бинарных данных в рапидскаду.

2018-01-07 12:09 GMT+05:00 2mik <notifications@github.com>:

**Comment by bersim** [comment]
New version KpMQTT for Rapid Scada 5.5.0 
Link for binary DLL: https://github.com/bersim/OpenKPs/releases/download/5.0.9/KpMQTT.7z

**Comment by 2mik** [comment]
Обновил ссылки в репозитории Rapid SCADA.
